[mypy]

strict = True
python_version = 3.12
cache_dir = $MYPY_CONFIG_FILE_DIR/.mypy_cache

files = $MYPY_CONFIG_FILE_DIR/packages/**/*.py,
        $MYPY_CONFIG_FILE_DIR/src/**/*.py,
        $MYPY_CONFIG_FILE_DIR/tests/**/*.py

exclude_gitignore = True
exclude = (?x)(
      ^examples/    # files in examples/
    )


warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unreachable = True

[mypy-optree]
ignore_missing_imports = True
