[mypy]

strict = True
python_version = 3.12

; packages = automatix,algebraic,morphata
files = $MYPY_CONFIG_FILE_DIR/packages/**/*.py,
        $MYPY_CONFIG_FILE_DIR/src/**/*.py,
        $MYPY_CONFIG_FILE_DIR/tests/**/*.py

cache_dir = $MYPY_CONFIG_FILE_DIR/.mypy_cache

exclude_gitignore = True
exclude = (?x)(
      ^examples/    # files in examples/
    )


warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unreachable = True

[mypy-optree]
ignore_missing_imports = True
[mypy-optree.*]
ignore_missing_imports = True

[mypy-jax]
ignore_missing_imports = True
[mypy-jax.*]
ignore_missing_imports = True

[mypy-torch]
ignore_missing_imports = True
[mypy-torch.*]
ignore_missing_imports = True

[mypy-equinox]
ignore_missing_imports = True

[mypy-dd]
ignore_missing_imports = True
[mypy-dd.*]
ignore_missing_imports = True

[mypy-wadler_lindig]
ignore_missing_imports = True
