[project]
name = "argus-automatix"
authors = [{ name = "Anand Balakrishnan", email = "anandbala1597@gmail.com" }]
description = "Symbolic (weighted) automata monitors"
version = "0.4.0"
requires-python = ">=3.12"

dependencies = [
  "typing-extensions",
  "jax>=0.8",
  "jaxtyping>=0.3",
  "equinox>=0.12",
  "numpy",
  "optree>=0.17.0",
  "bitarray>=3.8.0",
  "algebraic",
  "hoaparser",
  "networkx",
  "types-networkx",
  "attrs>=25.4.0",
  "logic-asts>=1.1.4",
]

[dependency-groups]
dev = [
  "beartype>=0.22.5",
  "black",
  "graphviz",
  "hypothesis>=6.0.0",
  "ipython",
  "isort",
  "mypy",
  "pytest>=9.0.0",
  "pytest-xdist>=3.8.0",
  "ruff",
  "sympy>=1.14.0",
  "ty",
  "zuban",
]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "automatix"

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
algebraic = { workspace = true }
hoaparser = { workspace = true }

[tool.mypy]
strict = true
show_error_codes = true
warn_unreachable = true
# files = ["tests/", "src/", "packages/"]
packages = ["automatix", "algebraic", "hoaparser", "sparx"]

[[tool.mypy.overrides]]
module = ["dd", "dd.*"]
ignore_missing_imports = true

[tool.zuban]
strict = true

[tool.ruff]
line-length = 127

[tool.ruff.lint]
extend-select = ["E", "F", "W", "N", "B", "ANN", "PYI", "I"]
extend-ignore = ["F722"]

[tool.ruff.lint.extend-per-file-ignores]
"*.py" = ["B905", "E203", "E501", "W291", "W293"]
"*.pyi" = ["B", "E501", "E701"]
"examples/**.py" = ["N806"]

[tool.pyright]
include = ["src", "examples", "tests", "packages"]
pythonVersion = "3.12"
pythonPlatform = "All"
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
reportAny = false
