[pytest]
minversion = "9.0"
addopts = [
  "--import-mode=importlib",
  "--jaxtyping-packages=automatix,algebraic,beartype.beartype",
]
testpaths = ["tests", "src", "packages/**/tests", "packages/**/src"]

markers = ["slow: mark test as slow."]
